spring:
  profiles:
    active: common,datasource, swagger, security, local, quartz
  config:
    name: application
  web:
    resources:
      static-locations: classpath:/static/
  liquibase:
    change-log: classpath*:db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: postgres
    clear-checksums: true
    drop-first: off
mybatis-plus:
  global-config:
    db-config:
      id-type: NONE
    banner: false
  mapper-locations: classpath*:mapper/**/*Mapper*.xml
  type-aliases-package: cn.virtual.coin.domain.dal.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
vuca:
  trace:
    enabled: true
    excludes:
knife4j:
  setting:
    enable-footer: true
quartz:
  job:
    enabled: true
    package: cn.virtual.coin.server.job