spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg.vuca.com:55432/virtual_coin?useSSL=false&serverTimezone=UTC
    username: v_coin
    password: Pass@w0rd_vCoin
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 256
      minimum-idle: 12
      connection-timeout: 60000
      max-lifetime: 540000
      idle-timeout: 540000
      connection-test-query: SELECT 1

server.websocket.enabled: true

sharding.rule:
  tables:
    logic-table: t_candlestick
    algorithm-columns: [symbol, period]
    actual-tables: [t_candlestick_symbol_1min]

coin.collector:
  symbols: [ethusdt]
  dialect: postgresql
  logic-table: t_candlestick